### ISSUE TITLE
Debug and release with wrong file size

### ISSUE THREAD

**Issue by paulocoutinhox** [lasote/conan-darwin-toolchain#8] opened 2019-03-19 18:04 UTC
Hi,

I think that have something wrong with debug/release version. The compiled binaries have wrong size. Debug version is bigger in all platforms, but only for iOS debug is smaller than Release, and Release is very big in file size. 

Debug: 47,1 mb
Release: 116,9 mb

See:

![image](https://user-images.githubusercontent.com/395096/54630187-069c6100-4a58-11e9-8e1a-0776cef448bc.png)

Can debug/release configuration be wrong in your project?

**Comment by theodelrieu** [comment] 2019-03-20 11:19
What are the compiler flags in both cases? I need a reproducible case, I cannot do much with an image.

**Comment by paulocoutinhox** [comment] 2019-03-20 15:32
Hi,

I have a full working example here:
https://github.com/ezored/ezored

Only clone and execute:

```
python make.py target ios_framework conan
python make.py target ios_framework build
python make.py target ios_framework package
```

Profile:
https://github.com/ezored/ezored/blob/master/files/targets/ios_framework/conan/profile/ezored_ios_framework_profile

Recipe:
https://github.com/ezored/ezored/blob/master/files/targets/ios_framework/conan/recipe/conanfile.py

Conan install with params (but it is the same for all - and only on iOS this problem happen):
https://github.com/ezored/ezored/blob/master/files/targets/ios_framework/verbs/conan.py#L55

**Comment by theodelrieu** [comment] 2019-03-20 17:08
This is most likely due to bitcode. In debug mode, there is only a marker whereas in release the whole bitcode is included in the binary.

**Comment by paulocoutinhox** [comment] 2019-03-20 17:14
Ok, so, there is no problem, is this?

**Comment by theodelrieu** [comment] 2019-03-20 17:48
Nope, I'm closing this one

**Closed as completed by theodelrieu** 2019-03-20 17:48 UTC
